# Windows ISO Debloat Script
# Dựa trên Windows-ISO-Debloater repository
# Tác giả: Generated by AI Assistant
# Mô tả: Script để debloat Windows ISO và tạo unattended setup

param(
    [Parameter(Mandatory=$true)]
    [string]$InputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$Verbose,
    
    [Parameter(Mandatory=$false)]
    [string]$WindowsVersion = "11",
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipTelemetryRemoval = $false,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipBloatwareRemoval = $false
)

# Cấu hình logging
$LogFile = Join-Path $OutputPath "debloat.log"
$ErrorLogFile = Join-Path $OutputPath "debloat-errors.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    if ($Verbose) {
        Write-Host $logMessage
    }
    
    Add-Content -Path $LogFile -Value $logMessage
}

function Write-ErrorLog {
    param([string]$Message, [string]$Exception = "")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $errorMessage = "[$timestamp] ERROR: $Message"
    if ($Exception) {
        $errorMessage += " Exception: $Exception"
    }
    
    Write-Host $errorMessage -ForegroundColor Red
    Add-Content -Path $ErrorLogFile -Value $errorMessage
}

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Mount-WindowsImage {
    param([string]$ImagePath, [string]$MountPath)
    
    try {
        Write-Log "Mounting Windows image: $ImagePath to $MountPath"
        
        # Tạo thư mục mount nếu chưa tồn tại
        if (!(Test-Path $MountPath)) {
            New-Item -ItemType Directory -Path $MountPath -Force | Out-Null
        }
        
        # Mount image sử dụng DISM
        $result = DISM.exe /Mount-Image /ImageFile:$ImagePath /Index:1 /MountDir:$MountPath /ReadOnly
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to mount image. DISM exit code: $LASTEXITCODE"
        }
        
        Write-Log "Successfully mounted Windows image"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to mount Windows image" $_.Exception.Message
        return $false
    }
}

function Dismount-WindowsImage {
    param([string]$MountPath)
    
    try {
        Write-Log "Dismounting Windows image from: $MountPath"
        
        # Commit changes và dismount
        $result = DISM.exe /Unmount-Image /MountDir:$MountPath /Commit
        if ($LASTEXITCODE -ne 0) {
            Write-Log "Warning: Failed to commit changes, attempting to discard"
            $result = DISM.exe /Unmount-Image /MountDir:$MountPath /Discard
        }
        
        Write-Log "Successfully dismounted Windows image"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to dismount Windows image" $_.Exception.Message
        return $false
    }
}

function Remove-WindowsComponents {
    param([string]$MountPath)
    
    try {
        Write-Log "Removing unnecessary Windows components..."
        
        # Danh sách các components cần remove
        $componentsToRemove = @(
            "Microsoft-Windows-InternetExplorer-Optional-Package",
            "Microsoft-Windows-InternetExplorer-Optional-WOW64-Package",
            "Microsoft-Windows-MediaPlayer-Package",
            "Microsoft-Windows-MediaPlayer-Package-WOW64",
            "Microsoft-Windows-TabletPCMath-Package",
            "Microsoft-Windows-MathRecognizer-Package",
            "Microsoft-Windows-Speech-TTS-Package",
            "Microsoft-Windows-Speech-TTS-WOW64-Package",
            "Microsoft-Windows-Speech-Recognition-Package",
            "Microsoft-Windows-Speech-Recognition-WOW64-Package"
        )
        
        foreach ($component in $componentsToRemove) {
            Write-Log "Removing component: $component"
            $result = DISM.exe /Image:$MountPath /Remove-Package /PackageName:$component /NoRestart
            if ($LASTEXITCODE -eq 0) {
                Write-Log "Successfully removed: $component"
            } else {
                Write-Log "Warning: Failed to remove $component (may not be present)"
            }
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to remove Windows components" $_.Exception.Message
        return $false
    }
}

function Remove-BloatwareApps {
    param([string]$MountPath)
    
    if ($SkipBloatwareRemoval) {
        Write-Log "Skipping bloatware removal as requested"
        return $true
    }
    
    try {
        Write-Log "Removing bloatware apps..."
        
        # Danh sách các app packages cần remove
        $appsToRemove = @(
            "Microsoft.3DBuilder",
            "Microsoft.BingFinance",
            "Microsoft.BingNews",
            "Microsoft.BingSports",
            "Microsoft.BingWeather",
            "Microsoft.GetHelp",
            "Microsoft.Getstarted",
            "Microsoft.MicrosoftOfficeHub",
            "Microsoft.MicrosoftSolitaireCollection",
            "Microsoft.MixedReality.Portal",
            "Microsoft.People",
            "Microsoft.SkypeApp",
            "Microsoft.WindowsAlarms",
            "Microsoft.WindowsFeedbackHub",
            "Microsoft.WindowsMaps",
            "Microsoft.ZuneMusic",
            "Microsoft.ZuneVideo"
        )
        
        foreach ($app in $appsToRemove) {
            Write-Log "Removing app: $app"
            $result = DISM.exe /Image:$MountPath /Remove-ProvisionedAppxPackage /PackageName:$app
            if ($LASTEXITCODE -eq 0) {
                Write-Log "Successfully removed: $app"
            } else {
                Write-Log "Warning: Failed to remove $app (may not be present)"
            }
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to remove bloatware apps" $_.Exception.Message
        return $false
    }
}

function Disable-Telemetry {
    param([string]$MountPath)
    
    if ($SkipTelemetryRemoval) {
        Write-Log "Skipping telemetry removal as requested"
        return $true
    }
    
    try {
        Write-Log "Disabling telemetry and tracking..."
        
        # Tạo registry file để disable telemetry
        $registryContent = @"
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DiagTrack]
"Start"=dword:00000004

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice]
"Start"=dword:00000004

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"AllowTelemetry"=dword:00000000
"@
        
        $registryFile = Join-Path $OutputPath "telemetry-disable.reg"
        $registryContent | Out-File -FilePath $registryFile -Encoding ASCII
        
        # Apply registry changes to mounted image
        Write-Log "Applying telemetry registry changes..."
        $result = DISM.exe /Image:$MountPath /Add-Driver /Driver:$registryFile
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Successfully applied telemetry registry changes"
        } else {
            Write-Log "Warning: Failed to apply telemetry registry changes"
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to disable telemetry" $_.Exception.Message
        return $false
    }
}

function Create-UnattendedSetup {
    param([string]$MountPath)
    
    try {
        Write-Log "Creating unattended setup configuration..."
        
        # Tạo file unattend.xml
        $unattendContent = @"
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="windowsPE">
        <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetupUILanguage>
                <UILanguage>en-US</UILanguage>
            </SetupUILanguage>
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
        <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <DiskConfiguration>
                <Disk wcm:action="add">
                    <CreatePartitions>
                        <CreatePartition wcm:action="add">
                            <Order>1</Order>
                            <Type>Primary</Type>
                            <Size>350</Size>
                        </CreatePartition>
                        <CreatePartition wcm:action="add">
                            <Order>2</Order>
                            <Type>Primary</Type>
                            <Extend>true</Extend>
                        </CreatePartition>
                    </CreatePartitions>
                    <ModifyPartitions>
                        <ModifyPartition wcm:action="add">
                            <Order>1</Order>
                            <PartitionID>1</PartitionID>
                            <Label>System</Label>
                            <Format>NTFS</Format>
                            <Active>true</Active>
                        </ModifyPartition>
                        <ModifyPartition wcm:action="add">
                            <Order>2</Order>
                            <PartitionID>2</PartitionID>
                            <Label>Windows</Label>
                            <Letter>C</Letter>
                            <Format>NTFS</Format>
                        </ModifyPartition>
                    </ModifyPartitions>
                    <DiskID>0</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                </Disk>
            </DiskConfiguration>
            <ImageInstall>
                <OSImage>
                    <InstallTo>
                        <DiskID>0</DiskID>
                        <PartitionID>2</PartitionID>
                    </InstallTo>
                    <InstallToAvailablePartition>false</InstallToAvailablePartition>
                    <WillShowUI>OnError</WillShowUI>
                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/NAME</Key>
                            <Value>Windows 11 Pro</Value>
                        </MetaData>
                    </InstallFrom>
                </OSImage>
            </ImageInstall>
            <UserData>
                <AcceptEula>true</AcceptEula>
                <ProductKey>
                    <Key>W269N-WFGWX-YVC9B-4J6C9-T83GX</Key>
                    <WillShowUI>OnError</WillShowUI>
                </ProductKey>
            </UserData>
        </component>
    </settings>
    <settings pass="specialize">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ComputerName>Windows11-Debloated</ComputerName>
            <TimeZone>UTC</TimeZone>
        </component>
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
    </settings>
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <UserAccounts>
                <LocalAccounts>
                    <LocalAccount wcm:action="add">
                        <Password>
                            <Value></Value>
                            <PlainText>true</PlainText>
                        </Password>
                        <Description>Administrator Account</Description>
                        <DisplayName>Administrator</DisplayName>
                        <Group>Administrators</Group>
                        <Name>Administrator</Name>
                    </LocalAccount>
                </LocalAccounts>
            </UserAccounts>
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <ProtectYourPC>1</ProtectYourPC>
                <SkipMachineOOBE>true</SkipMachineOOBE>
                <SkipUserOOBE>true</SkipUserOOBE>
            </OOBE>
            <AutoLogon>
                <Password>
                    <Value></Value>
                    <PlainText>true</PlainText>
                </Password>
                <Enabled>true</Enabled>
                <LogonCount>1</LogonCount>
                <Username>Administrator</Username>
            </AutoLogon>
        </component>
    </settings>
</unattend>
"@
        
        $unattendFile = Join-Path $MountPath "unattend.xml"
        $unattendContent | Out-File -FilePath $unattendFile -Encoding UTF8
        
        Write-Log "Successfully created unattended setup configuration"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to create unattended setup" $_.Exception.Message
        return $false
    }
}

function Copy-ISOFile {
    param([string]$SourcePath, [string]$DestinationPath)
    
    try {
        Write-Log "Copying ISO file from $SourcePath to $DestinationPath"
        
        # Tìm file ISO trong thư mục input
        $isoFiles = Get-ChildItem -Path $SourcePath -Filter "*.iso" -Recurse
        if ($isoFiles.Count -eq 0) {
            throw "No ISO files found in $SourcePath"
        }
        
        $sourceIso = $isoFiles[0].FullName
        $destIso = Join-Path $DestinationPath $isoFiles[0].Name
        
        Copy-Item -Path $sourceIso -Destination $destIso -Force
        Write-Log "Successfully copied ISO file: $($isoFiles[0].Name)"
        
        return $destIso
    }
    catch {
        Write-ErrorLog "Failed to copy ISO file" $_.Exception.Message
        return $null
    }
}

function Optimize-ISO {
    param([string]$IsoPath)
    
    try {
        Write-Log "Optimizing ISO file..."
        
        # Tạo file thông tin về ISO đã được debloat
        $isoInfo = @{
            OriginalFile = Split-Path $IsoPath -Leaf
            DebloatDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
            WindowsVersion = $WindowsVersion
            FeaturesRemoved = @(
                "Telemetry and tracking",
                "Bloatware apps",
                "Unnecessary Windows components"
            )
            UnattendedSetup = $true
            OOBEBypass = $true
        }
        
        $infoFile = Join-Path (Split-Path $IsoPath -Parent) "debloat-info.json"
        $isoInfo | ConvertTo-Json -Depth 3 | Out-File -FilePath $infoFile -Encoding UTF8
        
        Write-Log "Successfully optimized ISO file"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to optimize ISO" $_.Exception.Message
        return $false
    }
}

# Main execution
try {
    Write-Log "Starting Windows ISO debloat process..."
    Write-Log "Input Path: $InputPath"
    Write-Log "Output Path: $OutputPath"
    Write-Log "Windows Version: $WindowsVersion"
    
    # Kiểm tra quyền admin
    if (!(Test-Administrator)) {
        throw "This script requires administrator privileges"
    }
    
    # Tạo thư mục output nếu chưa tồn tại
    if (!(Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    }
    
    # Copy ISO file
    $isoFile = Copy-ISOFile -SourcePath $InputPath -Destination $OutputPath
    if (!$isoFile) {
        throw "Failed to copy ISO file"
    }
    
    # Tạo thư mục mount
    $mountPath = Join-Path $OutputPath "mount"
    if (Test-Path $mountPath) {
        Remove-Item -Path $mountPath -Recurse -Force
    }
    New-Item -ItemType Directory -Path $mountPath -Force | Out-Null
    
    # Mount Windows image
    if (!(Mount-WindowsImage -ImagePath $isoFile -MountPath $mountPath)) {
        throw "Failed to mount Windows image"
    }
    
    # Thực hiện debloat
    $success = $true
    
    if (!(Remove-WindowsComponents -MountPath $mountPath)) {
        $success = $false
    }
    
    if (!(Remove-BloatwareApps -MountPath $mountPath)) {
        $success = $false
    }
    
    if (!(Disable-Telemetry -MountPath $mountPath)) {
        $success = $false
    }
    
    if (!(Create-UnattendedSetup -MountPath $mountPath)) {
        $success = $false
    }
    
    # Dismount image
    if (!(Dismount-WindowsImage -MountPath $mountPath)) {
        $success = $false
    }
    
    # Optimize ISO
    if (!(Optimize-ISO -IsoPath $isoFile)) {
        $success = $false
    }
    
    # Cleanup
    if (Test-Path $mountPath) {
        Remove-Item -Path $mountPath -Recurse -Force
    }
    
    if ($success) {
        Write-Log "Windows ISO debloat completed successfully!"
        Write-Host "Debloat completed successfully! Output files in: $OutputPath" -ForegroundColor Green
        exit 0
    } else {
        throw "Some debloat operations failed. Check logs for details."
    }
}
catch {
    Write-ErrorLog "Critical error during debloat process" $_.Exception.Message
    Write-Host "Debloat failed! Check error logs for details." -ForegroundColor Red
    exit 1
}
finally {
    Write-Log "Debloat process finished"
} 