# Windows ISO Debloat Script
# Dựa trên Windows-ISO-Debloater repository
# Tác giả: Generated by AI Assistant
# Mô tả: Script để debloat Windows ISO và tạo unattended setup

param(
    [Parameter(Mandatory=$true)]
    [string]$InputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$IsVerbose,
    
    [Parameter(Mandatory=$false)]
    [string]$WindowsVersion = "11",
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipTelemetryRemoval = $false,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipBloatwareRemoval = $false,
    
    [Parameter(Mandatory=$false)]
    [switch]$DryRun = $false
)

# Cấu hình logging
$LogFile = Join-Path $OutputPath "debloat.log"
$ErrorLogFile = Join-Path $OutputPath "debloat-errors.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    if ($IsVerbose) {
        Write-Host $logMessage
    }
    
    Add-Content -Path $LogFile -Value $logMessage
}

function Write-ErrorLog {
    param([string]$Message, [string]$Exception = "")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $errorMessage = "[$timestamp] ERROR: $Message"
    if ($Exception) {
        $errorMessage += " Exception: $Exception"
    }
    
    Write-Host $errorMessage -ForegroundColor Red
    Add-Content -Path $ErrorLogFile -Value $errorMessage
}

function Mount-WindowsImage {
    param([string]$ImagePath, [string]$MountPath)
    
    try {
        Write-Log "Mounting Windows image: $ImagePath to $MountPath"
        
        # Kiểm tra file ISO tồn tại
        if (!(Test-Path $ImagePath)) {
            throw "ISO file not found: $ImagePath"
        }
        
        # Lấy thông tin file ISO
        $isoInfo = Get-Item $ImagePath
        Write-Log "ISO file size: $($isoInfo.Length) bytes"
        Write-Log "ISO file last modified: $($isoInfo.LastWriteTime)"
        
        # Lấy đường dẫn tuyệt đối
        $absoluteImagePath = (Resolve-Path $ImagePath).Path
        $absoluteMountPath = (Resolve-Path $MountPath).Path
        
        Write-Log "Absolute image path: $absoluteImagePath"
        Write-Log "Absolute mount path: $absoluteMountPath"
        
        # Kiểm tra thư mục mount
        if (!(Test-Path $absoluteMountPath)) {
            Write-Log "Creating mount directory: $absoluteMountPath"
            New-Item -ItemType Directory -Path $absoluteMountPath -Force | Out-Null
        }
        
        # Kiểm tra quyền truy cập
        Write-Log "Checking file access permissions..."
        try {
            $testAccess = [System.IO.File]::OpenRead($absoluteImagePath)
            $testAccess.Close()
            Write-Log "File access test passed"
        }
        catch {
            throw "Cannot access ISO file: $($_.Exception.Message)"
        }
        
        # Kiểm tra file ISO có phải là Windows ISO không
        Write-Log "Checking ISO file integrity with DISM..."
        $dismCheck = DISM.exe /Get-WimInfo /WimFile:"$absoluteImagePath" 2>&1
        Write-Log "DISM check output: $dismCheck"
        
        if ($LASTEXITCODE -ne 0) {
            Write-Log "DISM check failed with exit code: $LASTEXITCODE"
            # Thử mount trực tiếp nếu DISM check thất bại
            Write-Log "Attempting direct mount despite DISM check failure..."
        }
        
        # Mount image sử dụng DISM với đường dẫn tuyệt đối
        Write-Log "Mounting image with DISM..."
        $mountResult = DISM.exe /Mount-Image /ImageFile:"$absoluteImagePath" /Index:1 /MountDir:"$absoluteMountPath" /ReadOnly 2>&1
        Write-Log "DISM mount output: $mountResult"
        
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to mount image. DISM exit code: $LASTEXITCODE. Output: $mountResult"
        }
        
        Write-Log "Successfully mounted Windows image"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to mount Windows image" $_.Exception.Message
        return $false
    }
}

function Dismount-WindowsImage {
    param([string]$MountPath)
    
    try {
        Write-Log "Dismounting Windows image from: $MountPath"
        
        # Commit changes và dismount
        $result = DISM.exe /Unmount-Image /MountDir:$MountPath /Commit
        if ($LASTEXITCODE -ne 0) {
            Write-Log "Warning: Failed to commit changes, attempting to discard"
            $result = DISM.exe /Unmount-Image /MountDir:$MountPath /Discard
        }
        
        Write-Log "Successfully dismounted Windows image"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to dismount Windows image" $_.Exception.Message
        return $false
    }
}

function Remove-WindowsComponents {
    param([string]$MountPath)
    
    try {
        Write-Log "Removing unnecessary Windows components..."
        
        # Danh sách các components cần remove
        $componentsToRemove = @(
            "Microsoft-Windows-InternetExplorer-Optional-Package",
            "Microsoft-Windows-InternetExplorer-Optional-WOW64-Package",
            "Microsoft-Windows-MediaPlayer-Package",
            "Microsoft-Windows-MediaPlayer-Package-WOW64",
            "Microsoft-Windows-TabletPCMath-Package",
            "Microsoft-Windows-MathRecognizer-Package",
            "Microsoft-Windows-Speech-TTS-Package",
            "Microsoft-Windows-Speech-TTS-WOW64-Package",
            "Microsoft-Windows-Speech-Recognition-Package",
            "Microsoft-Windows-Speech-Recognition-WOW64-Package"
        )
        
        foreach ($component in $componentsToRemove) {
            Write-Log "Removing component: $component"
            $result = DISM.exe /Image:$MountPath /Remove-Package /PackageName:$component /NoRestart
            if ($LASTEXITCODE -eq 0) {
                Write-Log "Successfully removed: $component"
            } else {
                Write-Log "Warning: Failed to remove $component (may not be present)"
            }
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to remove Windows components" $_.Exception.Message
        return $false
    }
}

function Remove-BloatwareApps {
    param([string]$MountPath)
    
    if ($SkipBloatwareRemoval) {
        Write-Log "Skipping bloatware removal as requested"
        return $true
    }
    
    try {
        Write-Log "Removing bloatware apps..."
        
        # Danh sách các app packages cần remove
        $appsToRemove = @(
            "Microsoft.3DBuilder",
            "Microsoft.BingFinance",
            "Microsoft.BingNews",
            "Microsoft.BingSports",
            "Microsoft.BingWeather",
            "Microsoft.GetHelp",
            "Microsoft.Getstarted",
            "Microsoft.MicrosoftOfficeHub",
            "Microsoft.MicrosoftSolitaireCollection",
            "Microsoft.MixedReality.Portal",
            "Microsoft.People",
            "Microsoft.SkypeApp",
            "Microsoft.WindowsAlarms",
            "Microsoft.WindowsFeedbackHub",
            "Microsoft.WindowsMaps",
            "Microsoft.ZuneMusic",
            "Microsoft.ZuneVideo"
        )
        
        foreach ($app in $appsToRemove) {
            Write-Log "Removing app: $app"
            $result = DISM.exe /Image:$MountPath /Remove-ProvisionedAppxPackage /PackageName:$app
            if ($LASTEXITCODE -eq 0) {
                Write-Log "Successfully removed: $app"
            } else {
                Write-Log "Warning: Failed to remove $app (may not be present)"
            }
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to remove bloatware apps" $_.Exception.Message
        return $false
    }
}

function Disable-Telemetry {
    param([string]$MountPath)
    
    if ($SkipTelemetryRemoval) {
        Write-Log "Skipping telemetry removal as requested"
        return $true
    }
    
    try {
        Write-Log "Disabling telemetry and tracking..."
        
        # Tạo registry file để disable telemetry
        $registryContent = @"
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DiagTrack]
"Start"=dword:00000004

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice]
"Start"=dword:00000004

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"AllowTelemetry"=dword:00000000
"@
        
        $registryFile = Join-Path $OutputPath "telemetry-disable.reg"
        $registryContent | Out-File -FilePath $registryFile -Encoding ASCII
        
        # Apply registry changes to mounted image
        Write-Log "Applying telemetry registry changes..."
        $result = DISM.exe /Image:$MountPath /Add-Driver /Driver:$registryFile
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Successfully applied telemetry registry changes"
        } else {
            Write-Log "Warning: Failed to apply telemetry registry changes"
        }
        
        return $true
    }
    catch {
        Write-ErrorLog "Failed to disable telemetry" $_.Exception.Message
        return $false
    }
}

function Create-UnattendedSetup {
    param([string]$MountPath, [string]$WindowsVersion)
    
    try {
        Write-Log "Creating unattended setup configuration..."
        
        # Tạo file unattend.xml
        $unattendContent = @"
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="windowsPE">
        <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetupUILanguage>
                <UILanguage>en-US</UILanguage>
            </SetupUILanguage>
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
        <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <DiskConfiguration>
                <Disk wcm:action="add">
                    <CreatePartitions>
                        <CreatePartition wcm:action="add">
                            <Order>1</Order>
                            <Type>Primary</Type>
                            <Size>350</Size>
                        </CreatePartition>
                        <CreatePartition wcm:action="add">
                            <Order>2</Order>
                            <Type>Primary</Type>
                            <Extend>true</Extend>
                        </CreatePartition>
                    </CreatePartitions>
                    <ModifyPartitions>
                        <ModifyPartition wcm:action="add">
                            <Order>1</Order>
                            <PartitionID>1</PartitionID>
                            <Label>System</Label>
                            <Format>NTFS</Format>
                            <Active>true</Active>
                        </ModifyPartition>
                        <ModifyPartition wcm:action="add">
                            <Order>2</Order>
                            <PartitionID>2</PartitionID>
                            <Label>Windows</Label>
                            <Letter>C</Letter>
                            <Format>NTFS</Format>
                        </ModifyPartition>
                    </ModifyPartitions>
                    <DiskID>0</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                </Disk>
            </DiskConfiguration>
            <ImageInstall>
                <OSImage>
                    <InstallTo>
                        <DiskID>0</DiskID>
                        <PartitionID>2</PartitionID>
                    </InstallTo>
                    <InstallToAvailablePartition>false</InstallToAvailablePartition>
                    <WillShowUI>OnError</WillShowUI>
                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/NAME</Key>
                            <Value>Windows 11 Pro</Value>
                        </MetaData>
                    </InstallFrom>
                </OSImage>
            </ImageInstall>
            <UserData>
                <AcceptEula>true</AcceptEula>
                <ProductKey>
                    <Key>W269N-WFGWX-YVC9B-4J6C9-T83GX</Key>
                    <WillShowUI>OnError</WillShowUI>
                </ProductKey>
            </UserData>
        </component>
    </settings>
    <settings pass="specialize">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ComputerName>Windows11-Debloated</ComputerName>
            <TimeZone>UTC</TimeZone>
        </component>
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
    </settings>
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <UserAccounts>
                <LocalAccounts>
                    <LocalAccount wcm:action="add">
                        <Password>
                            <Value></Value>
                            <PlainText>true</PlainText>
                        </Password>
                        <Description>Administrator Account</Description>
                        <DisplayName>Administrator</DisplayName>
                        <Group>Administrators</Group>
                        <Name>Administrator</Name>
                    </LocalAccount>
                </LocalAccounts>
            </UserAccounts>
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <ProtectYourPC>1</ProtectYourPC>
                <SkipMachineOOBE>true</SkipMachineOOBE>
                <SkipUserOOBE>true</SkipUserOOBE>
            </OOBE>
            <AutoLogon>
                <Password>
                    <Value></Value>
                    <PlainText>true</PlainText>
                </Password>
                <Enabled>true</Enabled>
                <LogonCount>1</LogonCount>
                <Username>Administrator</Username>
            </AutoLogon>
        </component>
    </settings>
</unattend>
"@
        
        $unattendFile = Join-Path $MountPath "unattend.xml"
        $unattendContent | Out-File -FilePath $unattendFile -Encoding UTF8
        
        Write-Log "Successfully created unattended setup configuration"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to create unattended setup" $_.Exception.Message
        return $false
    }
}

function Copy-ISOFile {
    param([string]$SourcePath, [string]$DestinationPath)
    
    try {
        Write-Log "Copying ISO file from $SourcePath to $DestinationPath"
        
        # Tìm file ISO trong thư mục input
        $isoFiles = Get-ChildItem -Path $SourcePath -Filter "*.iso" -Recurse
        if ($isoFiles.Count -eq 0) {
            throw "No ISO files found in $SourcePath"
        }
        
        $sourceIso = $isoFiles[0].FullName
        $destIso = Join-Path $DestinationPath $isoFiles[0].Name
        
        Copy-Item -Path $sourceIso -Destination $destIso -Force
        Write-Log "Successfully copied ISO file: $($isoFiles[0].Name)"
        
        return $destIso
    }
    catch {
        Write-ErrorLog "Failed to copy ISO file" $_.Exception.Message
        return $null
    }
}

function Optimize-ISO {
    param([string]$IsoPath)
    
    try {
        Write-Log "Optimizing ISO file: $IsoPath"
        
        # Lấy đường dẫn tuyệt đối
        $absoluteIsoPath = (Resolve-Path $IsoPath).Path
        
        # Tạo file unattend.xml
        $unattendPath = Join-Path (Split-Path $absoluteIsoPath) "unattend.xml"
        Create-UnattendXML -Path $unattendPath -WindowsVersion $WindowsVersion
        
        # Tạo file autounattend.xml
        $autounattendPath = Join-Path (Split-Path $absoluteIsoPath) "autounattend.xml"
        Create-AutoUnattendXML -Path $autounattendPath -WindowsVersion $WindowsVersion
        
        Write-Log "ISO optimization completed successfully"
        return $true
    }
    catch {
        Write-ErrorLog "Failed to optimize ISO" $_.Exception.Message
        return $false
    }
}

# Main execution
try {
    # Tạo thư mục output nếu chưa tồn tại
    if (!(Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    }
    
    # Kiểm tra quyền admin
    if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
        Write-Error "This script requires Administrator privileges. Please run as Administrator."
        exit 1
    }
    
    Write-Log "Starting Windows ISO debloat process..."
    Write-Log "Input Path: $InputPath"
    Write-Log "Output Path: $OutputPath"
    Write-Log "Windows Version: $WindowsVersion"
    Write-Log "Dry Run: $DryRun"
    
    # Kiểm tra thư mục input
    if (!(Test-Path $InputPath)) {
        throw "Input directory not found: $InputPath"
    }
    
    # Tìm file ISO trong thư mục input
    $isoFiles = Get-ChildItem -Path $InputPath -Filter "*.iso" -Recurse
    if ($isoFiles.Count -eq 0) {
        throw "No ISO files found in input directory: $InputPath"
    }
    
    $isoFile = $isoFiles[0]
    Write-Log "Found ISO file: $($isoFile.Name)"
    
    if ($DryRun) {
        Write-Log "DRY RUN MODE - No actual operations will be performed"
        Write-Log "Would copy ISO file: $($isoFile.Name)"
        Write-Log "Would mount image to: $OutputPath\mount"
        Write-Log "Would remove Windows components"
        Write-Log "Would remove bloatware apps"
        Write-Log "Would disable telemetry"
        Write-Log "Would create unattended setup"
        Write-Log "Would dismount image"
        Write-Log "Would optimize ISO"
        Write-Log "DRY RUN completed successfully!"
        Write-Host "Dry run completed successfully!" -ForegroundColor Green
        exit 0
    }
    
    # Tạo thư mục output nếu chưa tồn tại
    if (!(Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    }
    
    # Copy ISO file
    Write-Log "Copying ISO file from $InputPath to $OutputPath"
    $outputIsoPath = Join-Path $OutputPath $isoFile.Name
    Copy-Item -Path $isoFile.FullName -Destination $outputIsoPath -Force
    Write-Log "Successfully copied ISO file: $($isoFile.Name)"
    
    # Tạo thư mục mount
    $mountPath = Join-Path $OutputPath "mount"
    if (!(Test-Path $mountPath)) {
        New-Item -ItemType Directory -Path $mountPath -Force | Out-Null
    }
    
    # Mount Windows image
    if (!(Mount-WindowsImage -ImagePath $outputIsoPath -MountPath $mountPath)) {
        throw "Failed to mount Windows image"
    }
    
    # Remove Windows components
    if (!(Remove-WindowsComponents -MountPath $mountPath)) {
        Write-Log "Warning: Failed to remove some Windows components"
    }
    
    # Remove bloatware apps
    if (!(Remove-BloatwareApps -MountPath $mountPath)) {
        Write-Log "Warning: Failed to remove some bloatware apps"
    }
    
    # Disable telemetry
    if (!$SkipTelemetryRemoval) {
        if (!(Disable-Telemetry -MountPath $mountPath)) {
            Write-Log "Warning: Failed to disable telemetry"
        }
    }
    
    # Create unattended setup
    if (!(Create-UnattendedSetup -MountPath $mountPath -WindowsVersion $WindowsVersion)) {
        Write-Log "Warning: Failed to create unattended setup"
    }
    
    # Dismount Windows image
    if (!(Dismount-WindowsImage -MountPath $mountPath)) {
        Write-Log "Warning: Failed to dismount Windows image properly"
    }
    
    # Optimize ISO
    if (!(Optimize-ISO -IsoPath $outputIsoPath)) {
        Write-Log "Warning: Failed to optimize ISO"
    }
    
    Write-Log "Debloat process completed successfully!"
    Write-Host "Debloat completed successfully!" -ForegroundColor Green
    exit 0
}
catch {
    $errorMessage = $_.Exception.Message
    Write-ErrorLog "Critical error during debloat process" $errorMessage
    Write-Host "Debloat failed! Check logs for details." -ForegroundColor Red
    Write-Host "Error: $errorMessage" -ForegroundColor Red
    exit 1
}
finally {
    Write-Log "Debloat process finished"
} 