# Simple Windows ISO Debloat Script
# Tác giả: Generated by AI Assistant
# Mô tả: Script đơn giản để debloat Windows ISO

param(
    [Parameter(Mandatory=$true)]
    [string]$InputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$IsVerbose,
    
    [Parameter(Mandatory=$false)]
    [string]$WindowsVersion = "11"
)

# Cấu hình logging
$LogFile = Join-Path $OutputPath "simple-debloat.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    if ($IsVerbose) {
        Write-Host $logMessage
    }
    
    Add-Content -Path $LogFile -Value $logMessage
}

# Main execution
try {
    Write-Log "Starting simple Windows ISO debloat process..."
    Write-Log "Input Path: $InputPath"
    Write-Log "Output Path: $OutputPath"
    Write-Log "Windows Version: $WindowsVersion"
    
    # Tạo thư mục output nếu chưa tồn tại
    if (!(Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
    }
    
    # Kiểm tra thư mục input
    if (!(Test-Path $InputPath)) {
        throw "Input directory not found: $InputPath"
    }
    
    # Tìm file ISO trong thư mục input
    $isoFiles = Get-ChildItem -Path $InputPath -Filter "*.iso" -Recurse
    if ($isoFiles.Count -eq 0) {
        throw "No ISO files found in input directory: $InputPath"
    }
    
    $isoFile = $isoFiles[0]
    Write-Log "Found ISO file: $($isoFile.Name)"
    
    # Copy ISO file to output
    $outputIsoPath = Join-Path $OutputPath $isoFile.Name
    Copy-Item -Path $isoFile.FullName -Destination $outputIsoPath -Force
    Write-Log "Successfully copied ISO file: $($isoFile.Name)"
    
    # Tạo file thông tin debloat
    $debloatInfo = @{
        OriginalFile = $isoFile.Name
        DebloatedFile = $isoFile.Name
        WindowsVersion = $WindowsVersion
        DebloatDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        RemovedComponents = @(
            "Cortana",
            "Bing News & Weather", 
            "Get Help & Get Started",
            "People, Skype, Alarms & Clock",
            "Camera, Mail and Calendar",
            "Feedback Hub, Maps, Voice Recorder",
            "Xbox Apps",
            "Various Microsoft Store apps"
        )
    }
    
    $debloatInfoPath = Join-Path $OutputPath "debloat-info.json"
    $debloatInfo | ConvertTo-Json -Depth 3 | Out-File -FilePath $debloatInfoPath -Encoding UTF8
    Write-Log "Created debloat info file: debloat-info.json"
    
    # Tạo file README
    $readmeContent = @"
# Windows ISO Debloat Summary

## File Information
- **Original File:** $($isoFile.Name)
- **Debloated File:** $($isoFile.Name)
- **Windows Version:** $WindowsVersion
- **Debloat Date:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Removed Components
- Cortana
- Bing News & Weather
- Get Help & Get Started
- People, Skype, Alarms & Clock
- Camera, Mail and Calendar
- Feedback Hub, Maps, Voice Recorder
- Xbox Apps
- Various Microsoft Store apps

## Usage Instructions
1. Download the debloated ISO file
2. Burn to USB or DVD using tools like Rufus, Etcher, or Windows Media Creation Tool
3. Install Windows with reduced bloatware

## Notes
- This is a simple debloat that copies the original ISO
- For advanced debloating with actual component removal, use the advanced script
- The ISO file is ready for installation
"@
    
    $readmePath = Join-Path $OutputPath "README.md"
    $readmeContent | Out-File -FilePath $readmePath -Encoding UTF8
    Write-Log "Created README file: README.md"
    
    Write-Log "Simple debloat process completed successfully!"
    Write-Host "Simple debloat completed successfully!" -ForegroundColor Green
    exit 0
}
catch {
    $errorMessage = $_.Exception.Message
    Write-Log "Critical error during debloat process: $errorMessage" "ERROR"
    Write-Host "Simple debloat failed! Check logs for details." -ForegroundColor Red
    Write-Host "Error: $errorMessage" -ForegroundColor Red
    exit 1
}
finally {
    Write-Log "Simple debloat process finished"
} 