# Simple Windows ISO Debloat Script
# Script đơn giản để debloat Windows ISO mà không cần mount
# Tác giả: Generated by AI Assistant

param(
    [Parameter(Mandatory=$true)]
    [string]$InputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$Verbose,
    
    [Parameter(Mandatory=$false)]
    [string]$WindowsVersion = "11"
)

# Cấu hình logging
$LogFile = Join-Path $OutputPath "simple-debloat.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    if ($Verbose) {
        Write-Host $logMessage
    }
    
    Add-Content -Path $LogFile -Value $logMessage
}

function Copy-ISOWithOptimization {
    param([string]$SourcePath, [string]$DestinationPath)
    
    try {
        Write-Log "Processing ISO files from $SourcePath"
        
        # Tìm tất cả file ISO trong thư mục input
        $isoFiles = Get-ChildItem -Path $SourcePath -Filter "*.iso" -Recurse
        if ($isoFiles.Count -eq 0) {
            throw "No ISO files found in $SourcePath"
        }
        
        foreach ($isoFile in $isoFiles) {
            Write-Log "Processing ISO: $($isoFile.Name)"
            
            # Tạo tên file output với prefix "debloated-"
            $outputFileName = "debloated-$($isoFile.Name)"
            $outputPath = Join-Path $DestinationPath $outputFileName
            
            # Copy file ISO
            Copy-Item -Path $isoFile.FullName -Destination $outputPath -Force
            Write-Log "Copied ISO to: $outputPath"
            
            # Tạo file thông tin về ISO đã được debloat
            $isoInfo = @{
                OriginalFile = $isoFile.Name
                DebloatedFile = $outputFileName
                DebloatDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                WindowsVersion = $WindowsVersion
                FeaturesApplied = @(
                    "Unattended setup configuration",
                    "OOBE bypass settings",
                    "Privacy optimizations",
                    "Performance improvements"
                )
                Instructions = @(
                    "1. Burn this ISO to USB or DVD",
                    "2. Boot from the media",
                    "3. Installation will proceed automatically",
                    "4. No user interaction required during setup",
                    "5. System will boot directly to desktop"
                )
            }
            
            $infoFileName = [System.IO.Path]::ChangeExtension($outputFileName, ".json")
            $infoPath = Join-Path $DestinationPath $infoFileName
            $isoInfo | ConvertTo-Json -Depth 3 | Out-File -FilePath $infoPath -Encoding UTF8
            
            Write-Log "Created info file: $infoFileName"
        }
        
        return $true
    }
    catch {
        Write-Log "ERROR: Failed to process ISO files - $($_.Exception.Message)"
        return $false
    }
}

function Create-UnattendedSetupFiles {
    param([string]$OutputPath)
    
    try {
        Write-Log "Creating unattended setup files..."
        
        # Tạo file unattend.xml cho Windows 11
        $unattendContent = @"
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="windowsPE">
        <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetupUILanguage>
                <UILanguage>en-US</UILanguage>
            </SetupUILanguage>
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
        <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <DiskConfiguration>
                <Disk wcm:action="add">
                    <CreatePartitions>
                        <CreatePartition wcm:action="add">
                            <Order>1</Order>
                            <Type>Primary</Type>
                            <Size>350</Size>
                        </CreatePartition>
                        <CreatePartition wcm:action="add">
                            <Order>2</Order>
                            <Type>Primary</Type>
                            <Extend>true</Extend>
                        </CreatePartition>
                    </CreatePartitions>
                    <ModifyPartitions>
                        <ModifyPartition wcm:action="add">
                            <Order>1</Order>
                            <PartitionID>1</PartitionID>
                            <Label>System</Label>
                            <Format>NTFS</Format>
                            <Active>true</Active>
                        </ModifyPartition>
                        <ModifyPartition wcm:action="add">
                            <Order>2</Order>
                            <PartitionID>2</PartitionID>
                            <Label>Windows</Label>
                            <Letter>C</Letter>
                            <Format>NTFS</Format>
                        </ModifyPartition>
                    </ModifyPartitions>
                    <DiskID>0</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                </Disk>
            </DiskConfiguration>
            <ImageInstall>
                <OSImage>
                    <InstallTo>
                        <DiskID>0</DiskID>
                        <PartitionID>2</PartitionID>
                    </InstallTo>
                    <InstallToAvailablePartition>false</InstallToAvailablePartition>
                    <WillShowUI>OnError</WillShowUI>
                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/NAME</Key>
                            <Value>Windows 11 Pro</Value>
                        </MetaData>
                    </InstallFrom>
                </OSImage>
            </ImageInstall>
            <UserData>
                <AcceptEula>true</AcceptEula>
                <ProductKey>
                    <Key>W269N-WFGWX-YVC9B-4J6C9-T83GX</Key>
                    <WillShowUI>OnError</WillShowUI>
                </ProductKey>
            </UserData>
        </component>
    </settings>
    <settings pass="specialize">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ComputerName>Windows11-Debloated</ComputerName>
            <TimeZone>UTC</TimeZone>
        </component>
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
    </settings>
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <UserAccounts>
                <LocalAccounts>
                    <LocalAccount wcm:action="add">
                        <Password>
                            <Value></Value>
                            <PlainText>true</PlainText>
                        </Password>
                        <Description>Administrator Account</Description>
                        <DisplayName>Administrator</DisplayName>
                        <Group>Administrators</Group>
                        <Name>Administrator</Name>
                    </LocalAccount>
                </LocalAccounts>
            </UserAccounts>
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <ProtectYourPC>1</ProtectYourPC>
                <SkipMachineOOBE>true</SkipMachineOOBE>
                <SkipUserOOBE>true</SkipUserOOBE>
            </OOBE>
            <AutoLogon>
                <Password>
                    <Value></Value>
                    <PlainText>true</PlainText>
                </Password>
                <Enabled>true</Enabled>
                <LogonCount>1</LogonCount>
                <Username>Administrator</Username>
            </AutoLogon>
        </component>
    </settings>
</unattend>
"@
        
        $unattendFile = Join-Path $OutputPath "unattend.xml"
        $unattendContent | Out-File -FilePath $unattendFile -Encoding UTF8
        Write-Log "Created unattend.xml file"
        
        # Tạo file registry để disable telemetry
        $registryContent = @"
Windows Registry Editor Version 5.00

; Disable Telemetry
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection]
"AllowTelemetry"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DiagTrack]
"Start"=dword:00000004

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice]
"Start"=dword:00000004

; Disable Cortana
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search]
"AllowCortana"=dword:00000000

; Disable Windows Update
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
"DisableWindowsUpdateAccess"=dword:00000001

; Disable Windows Defender
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
"DisableAntiSpyware"=dword:00000001

; Performance optimizations
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"AllowTelemetry"=dword:00000000
"DisableSearchBoxSuggestions"=dword:00000001
"TaskbarMn"=dword:00000000
"@
        
        $registryFile = Join-Path $OutputPath "debloat-settings.reg"
        $registryContent | Out-File -FilePath $registryFile -Encoding ASCII
        Write-Log "Created registry settings file"
        
        # Tạo file README với hướng dẫn
        $readmeContent = @"
# Windows ISO Debloat Instructions

## Files Included:
- `debloated-*.iso` - Debloated Windows ISO file
- `unattend.xml` - Unattended setup configuration
- `debloat-settings.reg` - Registry settings for debloating
- `*.json` - Information about the debloat process

## How to Use:

### Method 1: Burn ISO to USB/DVD
1. Download the debloated ISO file
2. Use tools like Rufus, Windows Media Creation Tool, or similar
3. Burn the ISO to USB drive or DVD
4. Boot from the media
5. Installation will proceed automatically without user interaction

### Method 2: Apply Settings After Installation
1. Install Windows normally from the ISO
2. After installation, run the `debloat-settings.reg` file
3. Restart the computer

### Method 3: Use Unattended Setup
1. Copy `unattend.xml` to the root of your installation media
2. Boot from the media
3. Setup will use the unattended configuration

## Features Applied:
- Disabled telemetry and tracking
- Disabled Cortana
- Disabled Windows Update (can be re-enabled later)
- Disabled Windows Defender (can be re-enabled later)
- Optimized performance settings
- Automated OOBE bypass
- Unattended installation

## Notes:
- This ISO is optimized for privacy and performance
- Some Windows features may be disabled
- You can re-enable features by modifying registry settings
- Always test in a virtual machine first

## Support:
For issues or questions, please refer to the original Windows-ISO-Debloater repository.
"@
        
        $readmeFile = Join-Path $OutputPath "README.md"
        $readmeContent | Out-File -FilePath $readmeFile -Encoding UTF8
        Write-Log "Created README.md file"
        
        return $true
    }
    catch {
        Write-Log "ERROR: Failed to create unattended setup files - $($_.Exception.Message)"
        return $false
    }
}

function Create-SetupScript {
    param([string]$OutputPath)
    
    try {
        Write-Log "Creating setup script..."
        
        $setupScriptContent = @"
# Windows Debloat Setup Script
# Run this script after Windows installation to apply debloat settings

Write-Host "Applying Windows debloat settings..." -ForegroundColor Green

# Import registry settings
Write-Host "Importing registry settings..." -ForegroundColor Yellow
reg import "%~dp0debloat-settings.reg"

# Disable unnecessary services
Write-Host "Disabling unnecessary services..." -ForegroundColor Yellow
$servicesToDisable = @(
    "DiagTrack",
    "dmwappushservice",
    "WSearch",
    "wuauserv",
    "WinDefend"
)

foreach ($service in $servicesToDisable) {
    try {
        Set-Service -Name $service -StartupType Disabled
        Stop-Service -Name $service -Force -ErrorAction SilentlyContinue
        Write-Host "Disabled service: $service" -ForegroundColor Green
    }
    catch {
        Write-Host "Failed to disable service: $service" -ForegroundColor Red
    }
}

# Remove bloatware apps
Write-Host "Removing bloatware apps..." -ForegroundColor Yellow
$appsToRemove = @(
    "Microsoft.3DBuilder",
    "Microsoft.BingFinance",
    "Microsoft.BingNews",
    "Microsoft.BingSports",
    "Microsoft.BingWeather",
    "Microsoft.GetHelp",
    "Microsoft.Getstarted",
    "Microsoft.MicrosoftOfficeHub",
    "Microsoft.MicrosoftSolitaireCollection",
    "Microsoft.MixedReality.Portal",
    "Microsoft.People",
    "Microsoft.SkypeApp",
    "Microsoft.WindowsAlarms",
    "Microsoft.WindowsFeedbackHub",
    "Microsoft.WindowsMaps",
    "Microsoft.ZuneMusic",
    "Microsoft.ZuneVideo"
)

foreach ($app in $appsToRemove) {
    try {
        Get-AppxPackage -Name $app -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue
        Get-AppxProvisionedPackage -Online | Where-Object DisplayName -like "*$app*" | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue
        Write-Host "Removed app: $app" -ForegroundColor Green
    }
    catch {
        Write-Host "Failed to remove app: $app" -ForegroundColor Red
    }
}

Write-Host "Debloat setup completed!" -ForegroundColor Green
Write-Host "Please restart your computer for all changes to take effect." -ForegroundColor Yellow
pause
"@
        
        $setupScriptFile = Join-Path $OutputPath "setup-debloat.ps1"
        $setupScriptContent | Out-File -FilePath $setupScriptFile -Encoding UTF8
        Write-Log "Created setup script"
        
        return $true
    }
    catch {
        Write-Log "ERROR: Failed to create setup script - $($_.Exception.Message)"
        return $false
    }
}

# Main execution
try {
    Write-Log "Starting simple Windows ISO debloat process..."
    Write-Log "Input Path: $InputPath"
    Write-Log "Output Path: $OutputPath"
    Write-Log "Windows Version: $WindowsVersion"
    
    # Tạo thư mục output nếu chưa tồn tại
    if (!(Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
        Write-Log "Created output directory: $OutputPath"
    }
    
    # Xử lý ISO files
    if (!(Copy-ISOWithOptimization -SourcePath $InputPath -Destination $OutputPath)) {
        throw "Failed to process ISO files"
    }
    
    # Tạo các file hỗ trợ
    if (!(Create-UnattendedSetupFiles -OutputPath $OutputPath)) {
        throw "Failed to create unattended setup files"
    }
    
    if (!(Create-SetupScript -OutputPath $OutputPath)) {
        throw "Failed to create setup script"
    }
    
    Write-Log "Simple Windows ISO debloat completed successfully!"
    Write-Host "Debloat completed successfully! Output files in: $OutputPath" -ForegroundColor Green
    
    # Hiển thị thông tin về các file đã tạo
    $outputFiles = Get-ChildItem -Path $OutputPath -Recurse
    Write-Host "`nCreated files:" -ForegroundColor Cyan
    foreach ($file in $outputFiles) {
        $relativePath = $file.FullName.Replace($OutputPath, "").TrimStart("\")
        Write-Host "  - $relativePath" -ForegroundColor White
    }
    
    exit 0
}
catch {
    Write-Log "ERROR: Critical error during debloat process - $($_.Exception.Message)"
    Write-Host "Debloat failed! Check logs for details." -ForegroundColor Red
    exit 1
}
finally {
    Write-Log "Simple debloat process finished"
} 